# Generated by Django 5.0.2 on 2024-03-03 04:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunSQL(
            sql=[("""
CREATE TABLE IF NOT EXISTS tasks (
    id integer primary key,
    name varchar not null,
    status bool
);
"""), ("""
CREATE TABLE IF NOT EXISTS categories (
    id integer primary key,
    name varchar
)
""")],
            reverse_sql=[("""
DROP TABLE IF EXISTS tasks;
"""), ("""
DROP TABLE IF EXISTS categories;
""")]
        )
    ]
