# Generated by Django 5.0.2 on 2024-03-05 02:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[(
"""
CREATE TABLE IF NOT EXISTS job_positions (
    id int primary key,
    name varchar
)
"""),(
"""
CREATE TABLE IF NOT EXISTS department (
    id int primary key,
    name varchar
)
"""
)],
            reverse_sql=[
(
"""
DROP TABLE IF EXISTS Tjob_positions
"""
), (
"""
DROP TABLE IF EXISTS department
"""
)
            ]
        )
    ]
