# Generated by Django 5.0.2 on 2024-03-05 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_auto_20240305_0206"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
(
"""
CREATE TABLE IF NOT EXISTS user_roles (
    user_id int primary key unique,
    job_positions_id int
)
"""
), (
"""
CREATE TABLE IF NOT EXISTS user_department (
    user_id int primary key unique,
    department_id
)
"""
)
            ],
            reverse_sql=[(
"""
DROP TABLE IF EXISTS user_roles
"""
            ), (
"""
DROP TABLE IF EXISTS user_department
"""
            )]
        )
    ]
